HOMEPAGE = "http://github.com/openbmc/phosphor-rest-server"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://${WORKDIR}/git/LICENSE;md5=fa818a259cbed7ce8bc2a22d35a464fc"

#SRC_URI += "git://github.com/openbmc/phosphor-rest-server"
#SRCREV = "dee2ef579be581abe0d7e1dc8873463029b30deb"
SRC_URI += "git://github.com/geissonator/phosphor-rest-server;branch=ldap"
SRCREV = "503813881f861bd4edebfea90cd76522d5708f3e"

